## Preprocessing

In [3]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [6]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [7]:
# Determine the number of unique values in each column of application_df
application_df.nunique()

# Encode categorical variables using pd.get_dummies()
application_df_encoded = pd.get_dummies(application_df)

# Split the preprocessed data into feature and target arrays, then into training and testing datasets
y = application_df_encoded['IS_SUCCESSFUL'].values
X = application_df_encoded.drop('IS_SUCCESSFUL', axis=1).values

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Scale the training and testing data
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 150  # Adjusted cutoff value

application_types_to_replace = list(application_type_counts[application_type_counts < cutoff].index)

print(application_types_to_replace)


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

['T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [10]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts that are greater than 1
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts_gt1 = classification_counts[classification_counts > 1]

print(classification_counts_gt1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [12]:
# Choose a cutoff value for the classifications
cutoff = 100

# Create a list of classifications to be replaced
classifications_to_replace = list(classification_counts[classification_counts <= cutoff].index)

# Replace classifications in the DataFrame
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to see if the replacement was successful
classification_counts_post_binning = application_df['CLASSIFICATION'].value_counts()
print(classification_counts_post_binning)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df)

# Display the first few rows of the new DataFrame with dummy variables
print(application_df_dummies.head())

   STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0       1     5000              1                   False
1       1   108590              1                   False
2       1     5000              0                   False
3       1     6692              1                   False
4       1   142590              1                   False

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  \
0                  True                 False                False
1                 False                 False                 True
2                 False                 False                False
3                 False                 False                 True
4                 False                 False                 True

   APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  ...  \
0                False                False                False  ...
1                False                False                False  ...
2                False                 True                False  ...
3                False                False                False  ...
4                False                False                False  ...

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0              False                   False                     False
1               True                   False                     False
2              False                   False                     False
3              False                    True                     False
4              False                   False                      True

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0               False             False                   False
1               False             False                   False
2               False             False                   False
3               False             False                   False
4               False             False                   False

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0            False              False                      True
1            False              False                      True
2            False              False                      True
3            False              False                      True
4            False              False                      True

   SPECIAL_CONSIDERATIONS_Y
0                     False
1                     False
2                     False
3                     False
4                     False

[5 rows x 51 columns]

In [14]:
# Define the features set 'X' by selecting all columns except 'IS_SUCCESSFUL'
X = application_df_dummies.drop('IS_SUCCESSFUL', axis=1).values

# Define the target set 'y' by selecting 'IS_SUCCESSFUL'
y = application_df_dummies['IS_SUCCESSFUL'].values


from sklearn.model_selection import train_test_split

# Splitting the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [18]:
import tensorflow as tf

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('int')  # or `.astype('float32')` for binary classification targets
y_test = y_test.astype('int')  # or `.astype('float32')`

import numpy as np

# Check for and handle NaNs
if np.isnan(X_train).any():
    X_train = np.nan_to_num(X_train)
if np.isnan(X_test).any():
    X_test = np.nan_to_num(X_test)

# Similarly for infinite values
if np.isinf(X_train).any():
    X_train = np.clip(X_train, a_min=-np.finfo(np.float32).max, a_max=np.finfo(np.float32).max)
if np.isinf(X_test).any():
    X_test = np.clip(X_test, a_min=-np.finfo(np.float32).max, a_max=np.finfo(np.float32).max)


# Determine the number of input features
n_features = X_train.shape[1]

# Define the model - deep neural net
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=n_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))  # 'sigmoid' for binary classification

# Check the structure of the model
nn.summary()

# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
fit_model = nn.fit(X_train, y_train, epochs=100)  # epochs is the number of iterations over the entire dataset

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                4080

 dense_4 (Dense)             (None, 30)                2430

 dense_5 (Dense)             (None, 1)                 31

=================================================================
Total params: 6541 (25.55 KB)
Trainable params: 6541 (25.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/100
WARNING:tensorflow:From C:\Users\lisal\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\lisal\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

858/858 [==============================] - 1s 765us/step - loss: 92850.6484 - accuracy: 0.4916
Epoch 2/100
858/858 [==============================] - 1s 743us/step - loss: 85028.8828 - accuracy: 0.5077
Epoch 3/100
858/858 [==============================] - 1s 729us/step - loss: 43109.1289 - accuracy: 0.5073
Epoch 4/100
858/858 [==============================] - 1s 735us/step - loss: 11672.4570 - accuracy: 0.5014
Epoch 5/100
858/858 [==============================] - 1s 726us/step - loss: 49942.3672 - accuracy: 0.5005
Epoch 6/100
858/858 [==============================] - 1s 739us/step - loss: 40571.6211 - accuracy: 0.4890
Epoch 7/100
858/858 [==============================] - 1s 726us/step - loss: 5583.6885 - accuracy: 0.5108
Epoch 8/100
858/858 [==============================] - 1s 731us/step - loss: 22345.2129 - accuracy: 0.4971
Epoch 9/100
858/858 [==============================] - 1s 735us/step - loss: 10111.6143 - accuracy: 0.5144
Epoch 10/100
858/858 [==============================] - 1s 740us/step - loss: 21577.2188 - accuracy: 0.4941
Epoch 11/100
858/858 [==============================] - 1s 729us/step - loss: 4615.2500 - accuracy: 0.5079
Epoch 12/100
858/858 [==============================] - 1s 736us/step - loss: 7957.8335 - accuracy: 0.4931
Epoch 13/100
858/858 [==============================] - 1s 734us/step - loss: 4558.7764 - accuracy: 0.5207
Epoch 14/100
858/858 [==============================] - 1s 742us/step - loss: 2755.0405 - accuracy: 0.5180
Epoch 15/100
858/858 [==============================] - 1s 731us/step - loss: 496.7626 - accuracy: 0.5275
Epoch 16/100
858/858 [==============================] - 1s 734us/step - loss: 1270.3724 - accuracy: 0.5010
Epoch 17/100
858/858 [==============================] - 1s 731us/step - loss: 109.1739 - accuracy: 0.5040
Epoch 18/100
858/858 [==============================] - 1s 748us/step - loss: 23.5105 - accuracy: 0.5320
Epoch 19/100
858/858 [==============================] - 1s 726us/step - loss: 0.6911 - accuracy: 0.5320
Epoch 20/100
858/858 [==============================] - 1s 726us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 21/100
858/858 [==============================] - 1s 727us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 22/100
858/858 [==============================] - 1s 744us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 23/100
858/858 [==============================] - 1s 725us/step - loss: 0.6911 - accuracy: 0.5320
Epoch 24/100
858/858 [==============================] - 1s 727us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 25/100
858/858 [==============================] - 1s 728us/step - loss: 0.6911 - accuracy: 0.5320
Epoch 26/100
858/858 [==============================] - 1s 734us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 27/100
858/858 [==============================] - 1s 734us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 28/100
858/858 [==============================] - 1s 724us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 29/100
858/858 [==============================] - 1s 747us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 30/100
858/858 [==============================] - 1s 727us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 31/100
858/858 [==============================] - 1s 732us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 32/100
858/858 [==============================] - 1s 732us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 33/100
858/858 [==============================] - 1s 746us/step - loss: 0.6911 - accuracy: 0.5320
Epoch 34/100
858/858 [==============================] - 1s 742us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 35/100
858/858 [==============================] - 1s 736us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 36/100
858/858 [==============================] - 1s 738us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 37/100
858/858 [==============================] - 1s 750us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 38/100
858/858 [==============================] - 1s 742us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 39/100
858/858 [==============================] - 1s 733us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 40/100
858/858 [==============================] - 1s 736us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 41/100
858/858 [==============================] - 1s 751us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 42/100
858/858 [==============================] - 1s 742us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 43/100
858/858 [==============================] - 1s 731us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 44/100
858/858 [==============================] - 1s 730us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 45/100
858/858 [==============================] - 1s 749us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 46/100
858/858 [==============================] - 1s 727us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 47/100
858/858 [==============================] - 1s 736us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 48/100
858/858 [==============================] - 1s 734us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 49/100
858/858 [==============================] - 1s 759us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 50/100
858/858 [==============================] - 1s 741us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 51/100
858/858 [==============================] - 1s 729us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 52/100
858/858 [==============================] - 1s 737us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 53/100
858/858 [==============================] - 1s 749us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 54/100
858/858 [==============================] - 1s 743us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 55/100
858/858 [==============================] - 1s 739us/step - loss: 0.6914 - accuracy: 0.5320
Epoch 56/100
858/858 [==============================] - 1s 734us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 57/100
858/858 [==============================] - 1s 746us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 58/100
858/858 [==============================] - 1s 726us/step - loss: 0.6914 - accuracy: 0.5320
Epoch 59/100
858/858 [==============================] - 1s 727us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 60/100
858/858 [==============================] - 1s 742us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 61/100
858/858 [==============================] - 1s 762us/step - loss: 0.6914 - accuracy: 0.5320
Epoch 62/100
858/858 [==============================] - 1s 735us/step - loss: 0.6914 - accuracy: 0.5320
Epoch 63/100
858/858 [==============================] - 1s 731us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 64/100
858/858 [==============================] - 1s 733us/step - loss: 0.6914 - accuracy: 0.5320
Epoch 65/100
858/858 [==============================] - 1s 752us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 66/100
858/858 [==============================] - 1s 742us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 67/100
858/858 [==============================] - 1s 743us/step - loss: 0.6913 - accuracy: 0.5299
Epoch 68/100
858/858 [==============================] - 1s 767us/step - loss: 0.6914 - accuracy: 0.5320
Epoch 69/100
858/858 [==============================] - 1s 736us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 70/100
858/858 [==============================] - 1s 745us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 71/100
858/858 [==============================] - 1s 735us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 72/100
858/858 [==============================] - 1s 768us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 73/100
858/858 [==============================] - 1s 745us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 74/100
858/858 [==============================] - 1s 749us/step - loss: 0.6914 - accuracy: 0.5320
Epoch 75/100
858/858 [==============================] - 1s 751us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 76/100
858/858 [==============================] - 1s 767us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 77/100
858/858 [==============================] - 1s 742us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 78/100
858/858 [==============================] - 1s 740us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 79/100
858/858 [==============================] - 1s 751us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 80/100
858/858 [==============================] - 1s 757us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 81/100
858/858 [==============================] - 1s 746us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 82/100
858/858 [==============================] - 1s 752us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 83/100
858/858 [==============================] - 1s 761us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 84/100
858/858 [==============================] - 1s 743us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 85/100
858/858 [==============================] - 1s 739us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 86/100
858/858 [==============================] - 1s 758us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 87/100
858/858 [==============================] - 1s 754us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 88/100
858/858 [==============================] - 1s 753us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 89/100
858/858 [==============================] - 1s 746us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 90/100
858/858 [==============================] - 1s 741us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 91/100
858/858 [==============================] - 1s 752us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 92/100
858/858 [==============================] - 1s 739us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 93/100
858/858 [==============================] - 1s 743us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 94/100
858/858 [==============================] - 1s 776us/step - loss: 0.6911 - accuracy: 0.5320
Epoch 95/100
858/858 [==============================] - 1s 744us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 96/100
858/858 [==============================] - 1s 745us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 97/100
858/858 [==============================] - 1s 749us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 98/100
858/858 [==============================] - 1s 756us/step - loss: 0.6913 - accuracy: 0.5320
Epoch 99/100
858/858 [==============================] - 1s 754us/step - loss: 0.6912 - accuracy: 0.5320
Epoch 100/100
858/858 [==============================] - 1s 760us/step - loss: 0.6913 - accuracy: 0.5320
215/215 - 0s - loss: 0.6908 - accuracy: 0.5341 - 208ms/epoch - 967us/step
Loss: 0.6908186078071594, Accuracy: 0.5341107845306396

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.8176 - accuracy: 0.4983 - 138ms/epoch - 643us/step
Loss: 0.8175994157791138, Accuracy: 0.49825072288513184

In [20]:
# Save the model as an HDF5 file
nn.save("my_model.h5")

C:\Users\lisal\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [21]:
from tensorflow.keras.models import load_model

# Load the model
loaded_nn = load_model("my_model.h5")